### ISSUE TITLE
Testset C came which one tasks in DCASE18?

### ISSUE THREAD

**Issue by Qoboty** [RicherMans/Datadriven-GPVAD#2]
Hi, Guys, This is a good job
In Dataset, test set C  came from  DCASE18,  but DCASE18 has 5 tasks. so, Teseset C come which task? Thanks

**Comment by RicherMans** [comment]
Hey there,
Its the Task4 Dataset as described [here](http://dcase.community/challenge2018/task-large-scale-weakly-labeled-semi-supervised-sound-event-detection).
I guess it's nearly identical (with some small exceptions) to this year's DCASE2021 Task4 validation dataset, where the 2018 Task4 development and eval datasets are combined. The dataset is now also called DESED dataset.

Just to state that clear, test C is the combination of Dcase2018 Task4 Development + evaluation sets, which are manually annotated.
