### ISSUE TITLE
The error about “python3 extract_features.py wavs.txt -o hdf5/balanced.h5”，too

### ISSUE THREAD

**Issue by TryHard-LL** [RicherMans/Datadriven-GPVAD#20]
Hi，thanks for your excellent work.
When I rerun the program, I have got some errors.
such as:
![image](https://user-images.githubusercontent.com/56581796/228173187-4b655d82-3e23-41fa-aedd-b817915f8388.png)

I check it as "python3 extract_feature.py wavs.txt -o hdf5/balanced.h5"， but I got other error:
![image](https://user-images.githubusercontent.com/56581796/228191170-0cde0afd-42f4-48e0-bb9d-4c0e6e5e3eaf.png)
![image](https://user-images.githubusercontent.com/56581796/228191197-53910fe8-c061-4fc4-b92d-86d862fffd05.png)

**Comment by TryHard-LL** [comment]
> Hi，thanks for your excellent work. When I rerun the program, I have got some errors. such as: ![image](https://user-images.githubusercontent.com/56581796/228173187-4b655d82-3e23-41fa-aedd-b817915f8388.png)
> 
> I check it as "python3 extract_feature.py wavs.txt -o hdf5/balanced.h5"， but I got other error: ![image](https://user-images.githubusercontent.com/56581796/228191170-0cde0afd-42f4-48e0-bb9d-4c0e6e5e3eaf.png) ![image](https://user-images.githubusercontent.com/56581796/228191197-53910fe8-c061-4fc4-b92d-86d862fffd05.png)

Does the AudioSet look like this?
![image](https://user-images.githubusercontent.com/56581796/228191646-0910b936-3361-41d1-806c-7723c5a89e49.png)

![image](https://user-images.githubusercontent.com/56581796/228191686-4c36cb43-68fd-4cb6-aa6f-8864fbf5fe00.png)
![image](https://user-images.githubusercontent.com/56581796/228191757-00742bb7-082e-4fee-996e-eb67e6644ed2.png)

![image](https://user-images.githubusercontent.com/56581796/228191797-7cdc5295-7f77-492b-831f-8c2fb55df7f3.png)

**Comment by TryHard-LL** [comment]
Looking forward to your reply, thank you

**Comment by RicherMans** [comment]
Hey,
so your error is already at the first screenshot, where you are not in the correct directory, such that it says: `extract_features.py no such file or directory`.

Second, the format I use is a "kaldi like scp", which has a fixed column named "filename" as the first row, somewhat  like this:

```bash
cat wav.txt

# filename
# a.wav
# b.wav
```

Third, 
> Does the AudioSet look like this?

Sorry that are baseline Audioset features. You need to download the `raw` wave files for training ( or evaluation ).

**Comment by TryHard-LL** [comment]
![image](https://user-images.githubusercontent.com/56581796/228193312-a566fd7b-e385-46cc-b3b7-848ad65a0228.png)
Sorry,
I don not find where the shell "extracts_feature.py" is.

**Comment by TryHard-LL** [comment]
> 

The raw wave files may be not published ~

**Comment by RicherMans** [comment]
> ![image](https://user-images.githubusercontent.com/56581796/228193312-a566fd7b-e385-46cc-b3b7-848ad65a0228.png) Sorry, I don not find where the shell "extracts_feature.py" is.

You need to run the script in this `data/` directory.

> The raw wave files may be not published ~ 

They are, just need to download them using i.e., some download tool. I recommend my own [here](https://github.com/RicherMans/UIT_Mobile/tree/main/datasets/audioset).

**Comment by TryHard-LL** [comment]
> > ![image](https://user-images.githubusercontent.com/56581796/228193312-a566fd7b-e385-46cc-b3b7-848ad65a0228.png) Sorry, I don not find where the shell "extracts_feature.py" is.
> 
> You need to run the script in this `data/` directory.
> 
> > The raw wave files may be not published ~
> 
> They are, just need to download them using i.e., some download tool. I recommend my own [here](https://github.com/RicherMans/UIT_Mobile/tree/main/datasets/audioset).

thank you very much!
